### ISSUE TITLE
Blog Lists/Blog Posts - Unable to create a nav section under a non navigation folder.  Error message appears

### ISSUE THREAD

**Issue by natechadwick** [percussion/percussioncms#563]
Behavior:  I get the following error message after trying to create a Blog List / Post under a folder (non-nav) section.  Apparently the code is not allowing for a nav section to be put under a non-nav folder.

Here is the error I get:

Attached is the server.log file for this error

Steps to reproduce:

Create 2 templates:  1 for Blog List and 1 for Blog post

Add the Blog List widget on to the blog list template and the blog post widget onto the blog post template.

Add the Blogs gadget on to the dashboard.

Create a folder under your root site.

From the Blogs gadget, create a new post.

Select the folder under the root site.  Give the blog a title and complete the wizard.

At Finish, the error will appear.

![blog-list](https://user-images.githubusercontent.com/1232206/181286950-921e4402-b8f2-41cb-995d-e54952462e5d.png)

**Comment by natechadwick** [comment]
The underlying issue for this was when the user tried to add a new blog to a non navigation (just regular) folder.  The code has been updated to add the blog as a section link to the closest parent navigation folder.  Blog folders are always navigation folders so they need a parent navigation node.

**Comment by NxPerc2019** [comment]
I tested this with the following nightly build of 8.1.1:
![image](https://user-images.githubusercontent.com/50147765/184008863-c5e6c9de-012e-4593-b50e-5b14148e4a60.png)

I think I am blocked testing Github 563 because I am still seeing 564.  I am NOT seeing the same error in 563 and it looks like it is creating a new section as Nates comments suggest, but I am not sure if that is enough for acceptance criteria as the blog list is never created due to being blocked by 564.

![image](https://user-images.githubusercontent.com/50147765/184009038-0dcc7543-4dd4-41cc-a168-8d17539a8f74.png)

**Comment by Yashdeep2001** [comment]
![image](https://user-images.githubusercontent.com/103224298/190241274-b5b071c8-bfe8-40b5-b4d7-eac63df7d174.png)
error no longer occurs
