### ISSUE TITLE
Blog List - An exception thrown when creating a blog list thru the gadget

### ISSUE THREAD

**Issue by natechadwick** [percussion/percussioncms#564]
An exception and error was thrown when creating a Blog List thru the Blog Gadget.  

Steps to reproduce:  Create a Blog List and Blog Post Template.

Add the Blog List Widget to the blog list template.

Add the Blog Post Widget to the blog post template.

Add the Blog gadget to the dashboard.

Create a new Blog using the Gadget and the error should appear.
![blog-assembly-error](https://user-images.githubusercontent.com/1232206/181288165-411a7ca6-a768-4aaa-8b9c-f61c784c2bd6.png)

**Comment by sonyDeswal** [comment]
It is happening due to Derby Error when executing following query:-

select percpage2_.CONTENTID as col_0_0_, percpage2_.REVISIONID as col_1_0_, parentfold1_.OWNER_ID as col_2_0_ from CONTENTSTATUS pscomponen0_ left outer join PSX_OBJECTRELATIONSHIP parentfold1_ on pscomponen0_.CONTENTID=parentfold1_.DEPENDENT_ID and parentfold1_.CONFIG_ID = 3 cross join CT_PAGE percpage2_ where pscomponen0_.CONTENTID=percpage2_.CONTENTID and pscomponen0_.CONTENTTYPEID=1001 and percpage2_.REVISIONID=pscomponen0_.CURRENTREVISION and (parentfold1_.OWNER_ID in (10083)) and percpage2_.TEMPLATEID='16777215-101-10082'

1) [Code: 40000, SQL State: 58009]  Network protocol exception: DSS length not 0 at end of same id chain parse.  The connection has been terminated.
2) [Code: 0, SQL State: XJ001]  DERBY SQL error: ERRORCODE: 0, SQLSTATE: XJ001, SQLERRMC: java.lang.ArrayIndexOutOfBoundsException21XJ001.U
