### ISSUE TITLE
Session doesn't time out and User session extension option also not available to user application wide

### ISSUE THREAD

**Issue by ramdev1980** [percussion/percussioncms#832]
**Describe the bug**
When user session times out , the pop up for extending the user session not available to user. And also session doesn't time out.

**To Reproduce**

Go to Widget Builder  (http://localhost:9992/cm/app/?view=widgetbuilder&pathType=unknown)
Leave the screen idle for the same duration which configured under <userSessionTimeout> tag in Config.xml file.
Session doesn't time out and Pop up for extending session not available to user 

**Expected behavior**
Session should time out after the screen is left idle for the interval specified  in Config.xml file gets over and a popup for extending session should appear.

**Additional context**
Navigate all the options available for similar issue and fix.

**Comment by ramdev1980** [comment]
@natechadwick 

I tried to understand the session management functionality by adding breakpoints and analyzing the following files, but no success:
PSUtilityRestService
PSUserSessionManager
perc_path_constants.js
system/config/config.xml

I need a KT on the session management functionality in CMS application before estimating on it.

**Comment by natechadwick** [comment]
@ramdev1980  I increased the estimate as it has already taken more than a day and it looks like the existing logic needs refactored. 

## Expected Behavior
If the user logs in and is using the UI but doesn't hit the server before the session timeout, they can be forced to logout with an expired server session and lose data. We want to ping the server before the session times out on the server if we haven't pinged the server in <SessionTimeout time and the user is active. 

 - Get server config for sessiontimeout and for session warning (save that in local storage)
 - Track when we last hit the server (save that in local storage)
 - Set a timer for the sessiontimeout on the client at sessiontimeout - warning)
   -  When timer fires display warning dialog.
      - Set timer to fire at session warning time when the dialog is rendered.  If button is not clicked in 5 minutes for example, redirect parent window to the logout screen. 
       - If user hits ok, call server to extend the session
